/*

 ! THIS IS THE SORTING ALGORITHM WHICH IS USED BY C++ STL SORT FUNCTION.

 ! THIS IS THE HYBRID SORTING ALGORITHM WHICH USES QUICK SORT, HEAP SORT AND INSERTION SORT


 * WORKING

 & 1) SABSE PEHLE YE QUICK SORT USE KARTA HAI AUR AGAR RECURSION DEPTH EK LIMIT(16) SE JADA HOJATA HAI TO HEAP SORT USE KARTA HAI
 & 2) AGAR ARRAY SIZE SMALL HAI TO INSERTION SORT USE HOTA HAI.

*/