/*

 ^ CAPACITY OF ARRAY AT THE LOCAL LEVEL IS 10^6
 ^ CAPACITY OF ARRAY AT THE GLOBAL LEVEL IS 10^7

 ^ CAPACITY OF BOOLEAN ARRAY AT THE LOCAL LEVEL IS 10^7
 ^ CAPACITY OF BOOLEAN ARRAY AT THE GLOBAL LEVEL IS 10^8



*/
